language: c

dist: xenial

script:
  - git ls-files src/ | xargs clang-format -i && git diff --exit-code
  - git ls-files test/ | xargs clang-format -i && git diff --exit-code
  - make
  - .bin/test

